---@meta
---@alias game.event.name "window_pos" | "window_size" | "window_close" | "window_refresh" | "window_focus" | "window_iconify" | "window_maximize" | "framebuffer_size" | "window_content_scale" | "key" | "char" | "char_mods" | "mouse_button" | "cursor_pos" | "cursor_enter" | "scroll" | "drop"
---@class game.event
---@field on_event                nil | fun(name: game.event.name, ...)
---@field on_window_pos           nil | fun(xpos: integer, ypos: integer)
---@field on_window_size          nil | fun(width: integer, height: integer)
---@field on_window_close         nil | fun()
---@field on_window_refresh       nil | fun()
---@field on_window_focus         nil | fun(focused: boolean)
---@field on_window_iconify       nil | fun(iconified: boolean)
---@field on_window_maximize      nil | fun(maximized: boolean)
---@field on_framebuffer_size     nil | fun(width: integer, height: integer)
---@field on_window_content_scale nil | fun(xscale: number, yscale: number)
---@field on_key                  nil | fun(key: game.input.key, scancode: integer, action: game.input.action, mods: integer)
---@field on_char                 nil | fun(codepoint: integer)
---@field on_char_mods            nil | fun(codepoint: integer, mods: integer)
---@field on_mouse_button         nil | fun(button: game.input.mouse_button, action: game.input.action, mods: integer)
---@field on_cursor_pos           nil | fun(xpos: number, ypos: number)
---@field on_cursor_enter         nil | fun(entered: boolean)
---@field on_scroll               nil | fun(xoffset: number, yoffset: number)
---@field on_drop                 nil | fun(paths: string[])
game.event = {}
